name: oso
description: "Health tracking app"
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  dio: ^5.8.0+1
  cronet_http: ^1.3.2
  cupertino_http: ^2.1.0
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  logger: ^2.5.0
  collection: ^1.19.1
  get_it: ^8.0.3
  dart_jsonwebtoken: ^3.2.0
  json_annotation: ^4.9.0
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  permission_handler: ^12.0.0+1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
#  drift_dev: ^2.26.1
  mobx_codegen: ^2.7.0
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  json_serializable: ^6.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie_files/
    - assets/configs/
    - assets/fonts/poppins/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
